name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore SalesTax.sln

      - name: Build solution
        run: dotnet build SalesTax.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test SalesTaxTests/SalesTaxTests.csproj --verbosity quiet

      - name: Publish app
        run: dotnet publish SalesPrompter/SalesPrompter.csproj --configuration Release --output ./publish

      - name: Upload published files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SalesTaxApp
          path: ./publish

  deploy:
    name: Deploy from Artifact
    runs-on: self-hosted
    needs: build-test-publish

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SalesTaxApp
          path: ${{ github.workspace }}\deploy

      - name: Show downloaded files
        run: |
          echo "Files downloaded to:"
          dir "${{ github.workspace }}\deploy"

      - name: Deploy to IIS (or test path)
        run: |
          echo "Deploying to target location..."
          if (Test-Path "C:\SalesPrompter") {
            Remove-Item "C:\SalesPrompter" -Recurse -Force
          }
          mkdir "C:\SalesPrompter"
          xcopy "${{ github.workspace }}\deploy\*" "C:\SalesPrompter" /s /e /y

      - name: Confirm copied files
        run: |
          echo "Verifying files in target folder:"
          dir "C:\SalesPrompter"
