name: Manual Deployment

on:
  workflow_run:
    workflows: ["Build and Publish Artifact"]  # Name of the other workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SalesTaxApp
          path: ${{ github.workspace }}\deploy

      - name: Show downloaded files
        run: dir "${{ github.workspace }}\deploy"

      - name: Deploy to IIS
        run: |
          if (Test-Path "C:\inetpub\wwwroot\SalesPrompter") {
            Remove-Item "C:\inetpub\wwwroot\SalesPrompter" -Recurse -Force
          }
          mkdir "C:\inetpub\wwwroot\SalesPrompter"
          xcopy "${{ github.workspace }}\deploy\*" "C:\inetpub\wwwroot\SalesPrompter" /s /e /y
